---
- name: Create data 1 folder for elasticsearch
  file: path=/opt/elasticsearch/data2 state=directory

- name: Create data 2 folder for elasticsearch
  file: path=/opt/elasticsearch/data1 state=directory

- name: Create driver esdata1 with volume
  command: docker volume create --driver local --opt device=/opt/elasticsearch/data1 esdata1

- name: Create driver esdata2 with volume
  command: docker volume create --driver local --opt device=/opt/elasticsearch/data2 esdata2

- name: Login to private registry
  docker_login:
     registry: "{{ docker_registry }}"
     username: "{{ docker_user }}"
     password: "{{ docker_pass }}"

- name: Check elasticsearch images existed?
  docker_image: name={{docker_registry}}/monitoring/elasticsearch:5.6.2
  ignore_errors: yes
  register: es_image

- name: pull elasticsearch image
  docker_image: name=docker.elastic.co/elasticsearch/elasticsearch:5.6.2
  when: es_image != 0

- name: Tag and push to private registry
  docker_image: 
     name: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
     repository: "{{ docker_registry }}/monitoring/elasticsearch:5.6.2"
     push: yes
  when: es_image != 0

- name: Remove image without tagging
  docker_image: state=absent name=docker.elastic.co/elasticsearch/elasticsearch:5.6.2
