---

- name: Copy Kibana Docker folder
  copy: src=dockerKB dest=/tmp/

- name: Copy Kibana Dockerfile
  template: src=Dockerfile.j2 dest=/tmp/dockerKB/Dockerfile

- name: Login to private registry
  docker_login:
     registry: "{{ docker_registry }}"
     username: "{{ docker_user }}"
     password: "{{ docker_pass }}"

- name: Check kibana images existed?
  docker_image: name={{ docker_registry }}/monitoring/kibana
  ignore_errors: yes
  register: kb_image
  
- name: Build kibana image
  docker_image: name=kibana path=/tmp/dockerKB state=present
  when: kb_image != 0

- name: Tag and push to private registry
  docker_image: 
     name: kibana
     repository: "{{docker_registry}}/monitoring/kibana"
     push: yes
  when: kb_image != 0

- name: Remove image without tagging
  docker_image: state=absent name=kibana