---

- name: Copy docker folder
  copy: src=dockerNginx dest=/tmp/

- name: Login to private registry
  docker_login:
     registry: "{{ docker_registry }}"
     username: "{{ docker_user }}"
     password: "{{ docker_pass }}"

- name: Build nginx image
  docker_image: name=nginx path=/tmp/dockerNginx state=present

- name: Tag and push to private registry
  docker_image: 
     name: nginx
     repository: "{{ docker_registry }}/monitoring/nginx"
     push: yes

- name: Remove image without tagging
  docker_image: state=absent name=nginx