---

- name: Copy docker folder
  copy: src=dockerES dest=/tmp/

- name: Copy docker compose file
  template: src=docker-compose.yml.j2 dest=/tmp/dockerES/docker-compose.yml

- name: Create data folder for elasticsearch
  file: path=/opt/elasticsearch/data2 state=directory

- name: Create data folder for elasticsearch
  file: path=/opt/elasticsearch/data1 state=directory

- name: Create driver esdata1 with volume
  command: docker volume create --driver local --opt device=/opt/elasticsearch/data1 esdata1

- name: Create driver esdata2 with volume
  command: docker volume create --driver local --opt device=/opt/elasticsearch/data2 esdata2

- name: vm.max_map_count=262144
  lineinfile: dest=/etc/sysctl.conf line='vm.max_map_count=262144' state=present

- name: Enable sysctl
  command: /usr/sbin/sysctl -p

- name: Login to private registry
  docker_login:
     registry: "{{ docker_registry }}"
     username: "{{ docker_user }}"
     password: "{{ docker_pass }}"

- name: pull elasticsearch image
  docker_image: name={{ docker_registry }}/monitoring/elasticsearch:5.6.2
 
- name: Stop and remove container elasticsearch_master
  docker:
    name: elasticsearch1
    image: "{{ docker_registry }}/monitoring/elasticsearch:5.6.2"
    state: absent

- name: Stop and remove container elasticsearch_node
  docker:
    name: elasticsearch2
    image: "{{ docker_registry }}/monitoring/elasticsearch:5.6.2"
    state: absent

- name: Start docker compose
  command: docker-compose -f /tmp/dockerES/docker-compose.yml up -d
    
  